panic-height: 40 # минимальная высота, после которой будет снижаться рассудок
sanity-decrease: 0.1 # скорость снижения рассудка
sanity-increase: 0.1 # скорость повышения рассудка
sanity-decrease-expansion: 0.1 # насколько увеличивается скорость снижения рассудка при каждом блоке, ниже минимальной высоты