main: "com.katok.besane.Besane"
name: Besane
version: 1.0
api-version: 1.16
author: Katok777
description: "Плагин на рассудок"
softdepend: [PlaceholderAPI]

permissions:
  besane.admin:
    default: op

commands:
  besane:
    usage: /besane <args>
    permission: besane.admin